=head1 NAME

libinnauth - Routines for writing nnrpd resolvers and authenticators

=head1 SYNOPSIS

    #include "libinnauth.h"

    struct res_info {
        char *clienthostname;
        char *clientip;
        char *clientport;
        char *localip;
        char *localport;
    };

    struct auth_info {
        char *username;
        char *password;
    };

    struct auth_info *get_auth_info(FILE *);
    struct res_info  *get_res_info (FILE *);

    void free_auth_info(struct auth_info*);
    void free_res_info (struct res_info*);

    void print_user(const char *);

=head1 DESCRIPTION

These functions provide a convenient C frontend to the nnrpd external
authentication interface documented in F<doc/external-auth>.  Use of
this library is B<not> required; in particular, external resolvers and
authenticators written in languages other than C will need to implement
the necessary functionality themselves.

The get_auth_info() and get_res_info() functions allocate sufficient
memory for a B<struct auth_info> or B<struct res_info> and any necessary
fields, and return a pointer to the struct with the fields filled in
from information supplied by nnrpd (the B<FILE*> parameter generally
should be C<stdin>).  Both functions return NULL on error.  The caller
is responsible for deallocating the memory by using the functions below.

The string fields of both structs are straightforward.  The B<clientip>,
B<clientport>, B<localip>, and B<localport> fields of B<struct res_info>
hold the client and local addresses and ports as text strings, rather
than as B<struct sockaddr> pointers.

The free_auth_info() and free_res_info() functions free the struct
passed in as argument and all necessary fields.

The print_user() function writes the given username to standard output
in the C<User:> format expected by nnrpd, terminated with a CRLF pair.
The string passed in should be exactly the username, with no extraneous
leading or trailing whitespace.

=head1 BUGS

In many cases, nnrpd provides more information than is normally useful
(for example, even when calling an authenticator, the resolver
information is often provided.)  On the other hand, in certain cases it
provides less information than might be expected (for example, if nnrpd
is reading from stdin rather than a socket).  The implementation is
capable of handling at least the first of these issues, but that
functionality is not exposed in the interface.

At present, F<libinnauth.h> and its implementation are located in
F<authprogs/>; perhaps they should be moved to F<include/> and F<lib/>,
respectively?

=head1 HISTORY

Written by Jeffrey S<M. Vinocur> <jeff@litech.org> for InterNetNews.

=head1 SEE ALSO

nnrpd(8), readers.conf(5), F<doc/external-auth>

=cut
