=head1 Upgrading from 2.2 to 2.3

This section is still a work in progress.  There may be additional things
to watch out for not listed here; if you run across any, please let
inn-bugs@isc.org know about them.

Simply doing a make update is not sufficient to upgrade; the history and
overview information will also have to be regenerated, since the formats
of both files have changed between 2.2 and 2.3.  Regardless of whether you
were using the storage API or traditional spool under 2.2, you'll need to
rebuild your overview and history files.

If you want to allow readers, or if you want to expire based on newsgroup
name, you need to tell INN to generate overview data and pick an overview
method by setting ovmethod in inn.conf.  See INSTALL and inn.conf(5) for
more details.

The code that generates the dbz index files has been split into a seperate
program, makedbz.  makehistory still generates the base history file and
the overview information, but some of its options have been changed.  To
rebuild the history and overview files, use:

    makehistory -b -f history.n -O -T/usr/local/news/tmp -l 600000

(Change the /usr/local/news/tmp path to some directory that has plenty of
temporary space, and leave off -O if you're running a transit-only server
and don't intend to expire based on group name, and therefore don't need
overview.)  This will generate a new history file as history.n and rebuild
overview at the same time.  If you want to preseve a record of expired
message IDs in the history file, run:

    awk 'NF==2 { print; }' < history >> history.n

to append them to the newly created history file.  Look over the new
history file and make sure it looks right, then generate the new index
files and move them into place:

    makedbz -s `wc -l <history.n` -f history.n
    mv history.n history
    mv history.n.dir history.dir
    mv history.n.hash history.hash
    mv history.n.index history.index

(Rather than .hash and .index files, you may have a .pag file if you're
using tagged hash.)

For a reader machine, F<nnrp.access> has been replaced by F<readers.conf>.
There currently isn't a program to convert between the old format and the
new format (if you'd like to contribute one, it would be welcomed
gratefully).  You may need to look over the sample F<readers.conf> and
readers.conf(5) to understand how to write a file equivalent to your
current F<nnrp.access>.

The flags for overchan have changed, plus you probably don't want to run
overchan at all any more.  Letting innd write overview data itself results
in somewhat slower performance, but is more reliable and has a better
failure mode under high loads.  Writing overview data directly is the
default, so in a normal upgrade from 2.2 to 2.3 you'll want to comment out
or remove your overchan entry in F<newsfeeds> and set useoverchan to false
in F<inn.conf>.

crosspost is no longer installed, and no longer works (even with
traditional spool).  If you have an entry for crosspost in F<newsfeeds>,
remove it.

=head1 Changes from 2.2 to 2.3

=over 2

=item *

New F<readers.conf> file (replaces F<nnrp.access>) which allows more
flexible specification of access restrictions.  Included in the sample
implementations is a RADIUS-based authenticator.

=item *

Unified overview has been replaced with an overview API, and there are now
three separate overview implementations to choose from.  One (tradindexed)
is very like traditional overview but uses an additional index file for
faster responses to readers.  The second (buffindexed) uses circular
buffers and can handle a higher incoming article rate while still being
fast for readers.  The third (ovdb) uses Berkeley DB to store overview
information (so you need to have Berkeley DB installed to use it).  The
ovmethod key in F<inn.conf> chooses the overview method to use.

=item *

All article storage and retrieval is now done via the storage API.
Traditional spool is now available as a storage type under the storage
API.

=item *

The timecaf storage method has been added, similar to timehash but storing
multiple articles in a single file.  See F<INSTALL> for details on it.

=item *

INN now supports embedded Python filters as well as Perl and TCL filters,
and supports Python authentication hooks.

=item *

There is preliminary support for news reading over SSL, using OpenSSL.

=item *

To simplify anti-abuse filtering, and to be more compliant with news
standards and proposed standards, INN now treats as control messages only
articles containing a Control header.  A Subject line beginning with
C<cmesg > is no longer sufficient for a message to be considered a control
message, and the Also-Control header is no longer supported.

=item *

The INN build system no longer uses subst.  This should be mostly
transparent to users, apart from the old annoyance of modifications to
include files being overridden again by subst when building INN being a
thing of the past.

=item *

The build and installation system has been substantially overhauled.  make
update now updates scripts as well as binaries and documentation, there is
better support for parallel builds (with make -j), there is less needless
make recursion, and far more of the system-dependent configuration is
handled directly by autoconf.  libtool build support (including shared
library support) should be better than previous releases.

=back

=head1 Changes from 2.1 to 2.2

=over 2

=item *

New storage.conf file (replaces storage.ctl).

=item *

New (optional) way of handling non-cancel control messages (controlchan)
that serializes them and prevents server overload from control message
storms.

=item *

Support for actsyncd to fetch active file with ftp; configured by default
to get the one at ftp://ftp.isc.org/pub/usenet/CONFIG/active.Z if you run
actsyncd.  Be sure to read the manual page for actsync to configure an
actsync.ign file for your site, and test simpleftp if you do not configure
with wget or ncftp.  Also see ftp://ftp.isc.org/pub/usenet/CONFIG/README.

=item *

Some options to configure are now moved to inn.conf (merge-to-groups and
pgp-verify).

=item *

inndf, a portable version of df(1) is supplied.

=item *

New cnfsstat program to show stats of cnfs buffers.

=item *

news2mail program for gateway'ing news into email is provided.

=item *

mailpost program for gateway'ing email to news is provided.

=item *

pullnews program for doing a sucking feed is provided (not meant for large
feeds).

=item *

The innshellvars.csh.in script is obsolete (and lives in the obsolete
directory, for now).

=back
