=head1 NAME

ovdb_recover - Perform recovery on the ovdb database, if needed

=head1 SYNOPSYS

ovdb_recover

=head1 DESCRIPTION

Attempts to open the ovdb database, and if the database needs recovery,
it attempts to perform the recovery.  Similar in function to the BerkeleyDB
F<db_recover> command.

Returns exit status of 0 if the database did not need recovery or if
recovery succeeded, and returns exit status 1 if recovery failed.  In
the latter case, the database may be damaged beyond repair, requiring
a rebuild with makehistory(8).

This command is normally called automatically by rc.news(8).

=head1 HISTORY

Written by Heath Kehoe E<lt>hakehoe@avalon.netE<gt> for InterNetNews.

=head1 SEE ALSO

ovdb(5), makehistory(8)

=cut
