=head1 NAME

ovdb_stat - Display information from the ovdb database

=head1 SYNOPSYS

B<ovdb_stat> B<-Hgci> [B<-r> I<artnumrange>] newsgroup [newsgroup ...]

B<ovdb_stat> B<-Hklmtv> [B<-d> I<database>]

=head1 DESCRIPTION

B<ovdb_stat> displays information from the ovdb database:  S<Berkeley DB>
statistics, newsgroup data, and overview records; and optionally
outputs in HTML format.

=head1 OPTIONS

=over 4

=item B<-g>

Newsgroup himark, lowmark, article count, and flag for the given newsgroups
(as stored in the ovdb "groupinfo" database) are displayed.

=item B<-c>

Similar to B<-g>, except the himark, lowmark, and count are calculated
by actually scanning the overview records and counting them.
This can be a lengthy operation on groups with lots of articles.

=item B<-i>

Internal data regarding the given newsgroups are displayed.

=item B<-r> I<artnumrange>

Overview records are retrieved.  The I<artnumrange> parameter may be
a single article number, or a range of articles in the format C<low-hi>.

=item B<-H>

Output is presented in HTML format.

=item B<-k>

Displays lock region statistics, as returned by the S<Berkeley DB> lock_stat()
call.

=item B<-l>

Displays log region statistics, as returned by the S<Berkeley DB> log_stat()
call.

=item B<-m>

Displays global memory pool statistics, as returned by the
S<Berkeley DB> memp_stat() call.

=item B<-M>

Same as B<-m>, and also displays memory pool statistics for each
database file.

=item B<-t>

Displays log region statistics, as returned by the S<Berkeley DB> txn_stat()
call.

=item B<-v>

Displays ovdb version, and S<Berkeley DB> version.

=item B<-d> I<database>

Displays information about the given database, as returned by the
S<Berkeley DB> db->stat() call.  This operation may take a long time
on busy systems (several minutes or more).

=back

=head1 WARNINGS

ovdb_stat may be safely killed with the INT, TERM, or HUP signals.
It catches those signals and exits cleanly.
Do not kill ovdb_stat with other signals, unless absolutely necessary,
because it may leave stale locks in the DB environment.

=head1 HISTORY

Written by Heath Kehoe E<lt>hakehoe@avalon.netE<gt> for InterNetNews.

$Id$

=head1 SEE ALSO

ovdb(5)

=cut
