=head1 NAME

sendinpaths - Send Usenet Path statistics via e-mail

=head1 SYNOPSIS

B<sendinpaths> [B<-n>]

=head1 DESCRIPTION

B<sendinpaths> checks I<pathlog>/path for B<ninpaths> dump files, and for
each valid dump file generated in the past 30 days (checked by running
B<ninpaths> on it and making sure B<ninpaths> exits with a zero exit
status), pass it to B<ninpaths> to generate a cumulative report.  Mail
that report to the e-mail addresses configured at the beginning of this
script (by default pathsurvey@top1000.org and top1000@anthologeek.net).

When finished, B<sendinpaths> deletes all dump files in I<pathlog>/path
that are older than 14 days (configurable at the beginning of the script).

For more information on how to set up B<ninpaths>, see ninpaths(8).

=head1 OPTIONS

=over 4

=item B<-n>

Don't e-mail the report; instead, just print it to standard output.  Don't
delete old dump files.

=back

=head1 SEE ALSO

ninpaths(8)

=head1 AUTHOR

Olaf Titz <olaf@bigred.inka.de>

=cut
