=head1 NAME

subscriptions - Default recommended subscriptions

=head1 DESCRIPTION

The I<pathetc>/F<subscriptions> file contains a list of newsgroups that is
returned by the NNTP command LIST SUBSCRIPTIONS.

Clients that support this command and send it the first time they connect
to a new news server use the returned list to initialize the list of
subscribed newsgroups.  The F<subscriptions> file therefore should contain
groups intented for new users, for testing, or that contain FAQs and other
useful information for first-time Usenet users.

The syntax of the F<subscriptions> file is trivial; it is a simple list of
newsgroup names, one per line.  The order of newsgroups may be
significant; the news reading client may present the groups in that order
to the user.

=head1 EXAMPLE

A typical F<subscriptions> file may look like:

    news.announce.newusers
    news.newusers.questions
    local.test
    local.general
    local.talk
    misc.test
    misc.test.moderated
    news.answers
    news.announce.newgroups

This gives the client the FAQs and question newsgroup for new users first,
then a local newsgroup for testing and various commonly-read local
discussion groups, followed by the world-wide test groups, all the FAQs,
and announcements of new world-wide newsgroups.  If there is a local new
users group, one might want to list it first.

=head1 HISTORY

Written by Bettina Fink <laura@hydrophil.de> for InterNetNews.

$Id$

=head1 SEE ALSO

nnrpd(8).

=cut
