#!/sbin/sh

# This is a simple, bare-bones example of a SysV-style init.d script for INN.
# It tries to increase the file descriptor limits to the maximum allowed by
# the system since INN and related programs can be file descriptor hogs.

case $1 in

start)
    ulimit -n unlimited
    su news -c /usr/local/news/bin/rc.news
    ;;

stop)
    su news -c '/usr/local/news/bin/rc.news stop'
    ;;

esac

exit 0

