/* Automatically generated by mkversion, edit Makefile.global to change. */

#ifndef _INN_VERSION_H
#define _INN_VERSION_H

#define INN_VERSION_MAJOR 2
#define INN_VERSION_MINOR 3
#define INN_VERSION_PATCH 1
#define INN_VERSION_EXTRA ""
#define INN_VERSION_STRING "INN 2.3.1"

#endif /*_INN_VERSION_H*/
