.\" $Revision$
.TH CONTROLCHAN 8
.SH NAME
controlchan \- channel\-fed control message handler
.SH SYNOPSIS
.B controlchan
.SH DESCRIPTION
.I Controlchan
removes the responsibility for handling control messages
(except cancels) from
.IR innd (8)
and instead processes them from a channel or file feed.
To reduce load,
.I controlchan
keeps a copy of
.IR control.ctl (5)
in memory and checks permissions (including any required PGP headers) before any
scripts are called.  Also, the default ("bad message") case is handled
internally.  The "drop" case is handled with far less fuss.
.PP
Normally,
.I controlchan
is configured in
.IR newsfeeds (5)
and invoked from
.IR innd (8).
And you need to set <usecontrolchan in inn.conf> to ``true''.
.I Controlchan
reports all log message through
.IR syslog (3),
if possible.  To enable syslogging, you will need to have run ``h2ph'' on your
system include files at some point (this is required to
make Sys::Syslog work).  If you have not done so, do this:
.sp 1
.nf
.in +0.5i
cd /usr/include
h2ph * sys/*
.in -0.5i
.fi
.SH HISTORY
Written by Katsuhiro Kondou <kondou@nec.co.jp> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
control.ctl(5),
inn.conf(5).
