.\" $Revision$
.TH CONVDATE 1
.SH NAME
convdate \- convert time/date strings and numbers
.SH SYNOPSIS
.B convdate
[
.B \-c
]
[
.B \-n
]
[
.B \-s
]
.I arg...
.SH DESCRIPTION
.I Convdate
translate the date/time strings specified as arguments on its
command line, outputting the results one to a line.
.SH OPTIONS
.TP
.B \-c
If the ``\fB\-c\fP'' flag is used, then each argument is taken to be a
.I time_t
and is output in
.I ctime
format.
.TP
.B \-n
If the ``\fB\-n\fP'' flag is used, then each argument is taken as a 
date string to be parsed by
.IR parsedate (3)
and is output as a
.IR time_t ;
see
.IR time (2).
.TP
.B \-s
If the ``\fB\-s\fP'' flag is used, then each argument is taken as a
date string to be parsed by
.IR parsedate (3)
and is output as a string formatted by
.IR ctime (3).
This is the default.
.SH EXAMPLES
.RS
.nf
.RI "% " "convdate 'feb 10 10am'"
Sun Feb 10 10:00:00 1991

.RI "% " "convdate 12pm 5/4/90"
Fri Dec 13 00:00:00 1991
Fri May  4 00:00:00 1990

.RI "% " "convdate -n 'feb 10 10am' '12pm 5/4/90'"
666198000
641880000

.RI "% " "convdate -c 666198000"
Sun Feb 10 10:00:00 1991
.fi
.RE
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net>.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
parsedate(3).
