.\" $Revision$
.TH NEWS-RECOVERY 8
.SH NAME
makeactive, makehistory, newsrequeue \- tools to recover Usenet databases
.SH SYNOPSIS
These man pages have been split out into separate pages.
.SH "SEE ALSO"
active(5),
ctlinnd(8),
dbz(3),
filechan(8),
history(5),
innd(8),
newsfeeds(5),
makehistory(8),
makeactive(8),
newsrequeue(8).
