.TH STARTINNFEED 8 "Nov 7, 1997"
.SH NAME
startinnfeed \- setuid root program to start innfeed
.SH SYNOPSIS
.B startinnfeed
.RB innfeed-options
.SH DESCRIPTION
.B Startinnfeed
sets all resources (files opened, memory usage) to unlimited. It then executes
innfeed(8) with the options specified.
.SH AUTHOR
James Brister
.SH "SEE ALSO"
.BR innfeed (8)
