.TH ACTIVED 8
.SH NAME
actived \- a daemon to handle nnrpd requests for active file information.
.SH SYNOPSIS
.B actived
.SH DESCRIPTION
.I Actived
is a process that keeps an in-memory copy of the news
.I active(5)
file along with its hashed index and serves requests for active file
information from
.I nnrpd(8)
clients. This saves significants amounts of memory for each nnrpd
client and also reduces its startup time as it no longer needs to
index the active file. The process is able to handle many requests
as second and should improve the overall performance of news reader
machines.
.PP
Actived is enabled with the ``activedenable'' option in
.I inn.conf(5)
and is started by
.I inndstart(8).
The ``activedupdate'' option determines how often
the in-memory copy of the active file is updated and the ``activedport''
option allows one to specify the UDP port to send/receive requests.
.PP
The process writes its process ID into a file pathrun/actived.pid
on startup. The process remains active until killed manually. If it
is killed or dies for some reason, clients will revert to direct
access to the active file, which will be a lot slower.
.SH "SEE ALSO"
inndstart(8),
nnrpd(8),
inn.conf(5),
active(5).
