.\" $Revision$
.TH CROSSPOST 8
.SH NAME
crosspost \- create the links for cross posted articles
.SH SYNOPSIS
The
.B crosspost
program is obsolete.  The tradspool storage method will make file links
as appropriate inside the
.IR innd (8)
process.
.SH HISTORY
Originally written by Jerry Aguirre <jerry@ATC.Olivetti.Com>.
