.\" $Revision$
.TH EXPIREOVER 8
.SH NAME
expireover \- Expire entries from the news overview database
.SH SYNOPSIS
.B expireover
[
.BI \-f " file"
]
[
.BI \-Z " lofile"
]
.SH DESCRIPTION
.I Expireover
expires entries from the news overview database.
It reads a list of newsgroup list (
.IR <pathdb\ in\ inn.conf>/active ).
(A file name of ``\-'' may be used to specify the standard input.)
It then removes any mention of those articles from the appropriate overview
database.
.SH OPTIONS
.TP
.B \-f
When the ``\fB\-\fPs'' flag is used, then
.I expireover
will use it as newsgroup list instead of
.IR active (5)
file.
To specify an alternate file, use the ``\fB\-f\fP'' flag; a name 
of ``\fB\-\fP'' is
taken to mean the standard input.
.TP
.B \-Z
If the ``\fB\-Z\fP'' flag is used, then the lowest article numbers for
each newsgroup are written to the specified file.
This flag can be usable when doing ``ctlinnd lomark lofile''.
.SH HISTORY
Written by Rob Robertson <rob@violet.berkeley.edu>
and Rich $alz <rsalz@uunet.uu.net>
(with help from Dave Lawrence <tale@uunet.uu.net>)
for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
expire(8),
inn.conf(5).
