.\" $Revision$
.TH EXPIREOVER 8
.SH NAME
expireover \- Expire entries from the news overview database
.SH SYNOPSIS
.B expireover
[
.B \-a
]
[
.BI \-D " overviewdir"
]
[
.BI \-f " file"
]
[
.B \-n
]
[
.BI \-O " overview.fmt"
]
[
.B \-q
]
[
.B \-s
]
[
.B \-v
]
[
.B \-z
]
[
.I file...
]
.SH DESCRIPTION
.I Expireover
expires entries from the news overview database.
It reads a list of pathnames (relative to the spool directory,
.\" =()<.IR @<_PATH_SPOOL>@ ),>()=
.IR /var/news/spool/articles ),
from the specified
.I files
or standard input if none are specified.
(A file name of ``\-'' may be used to specify the standard input.)
It then removes any mention of those articles from the appropriate overview
database.
.PP
If you have turned on the storage manager with the 'storageapi' in inn.conf (5),
you need to use expireindex (8) to expire overveiw index.
.SH OPTIONS
.TP
.B \-a
The ``\fB\-a\fP'' flag reads the spool directory and adds any missing
overview entries.
It will create files if necessary.
This can be used to initialize a database, or to sync up a overview
database that may be lacking articles due to a crash.
.I Overchan
should be running, to ensure that any incoming articles get included.
Using this flag implies the ``\fB\-s\fP'' flag; 
the ``\fB\-f\fP'' flag may be used
to add only a subset of the newsgroups.
.TP
.B \-D
The ``\-D'' flag can be used to specify where the databases are stored.
The default directory is
.\" =()<.IR @<_PATH_OVERVIEWDIR>@ .>()=
.IR /var/news/spool/over.view .
.TP
.B \-f
When the ``\fB\-\fPs'' flag is used, then
.I expireover
will read the spool directory for all groups mentioned in the
.IR active (5)
file.
To specify an alternate file, use the ``\fB\-f\fP'' flag; a name 
of ``\fB\-\fP'' is
taken to mean the standard input.
.TP
.B \-n
To perform no real updates, use the ``\fB\-n\fP'' flag.
.TP
.B \-O
The ``\fB\-O\fP'' flag may be used to specify an alternate location for the
.IR overview.fmt (5)
file; this is normally only useful for debugging.
.TP
.B \-q
Not to tell lock file open failure, use the ``\fB\-q\fP'' flag.
.TP
.B \-s
If the ``\fB\-\fPs'' flag is used, then
.I expireover
will read the spool directory for all groups mentioned in the
.IR active (5)
file, and remove the overview entries of any articles that do not appear
in the directory.
.TP
.B \-v
To see a list of the entries that would be added or deleted, use 
the ``\fB\-v\fP''
flag.
.TP
.B \-z
If the ``\fB\-z\fP'' flag is used, then the input is assumed to be sorted such
that all entries for a newsgroup appear together so that it can be purged
at once.
This flag can be useful when used with the sorted output of
.IR expire (8)'s
\&``\fB\-z\fP'' flag.
.SH HISTORY
Written by Rob Robertson <rob@violet.berkeley.edu>
and Rich $alz <rsalz@uunet.uu.net>
(with help from Dave Lawrence <tale@uunet.uu.net>)
for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
expire(8),
expireindex(8),
overview.fmt(5).
