.\" $Revision$
.TH EXPIRE 8
.SH NAME
expire \- Usenet article and history expiration program
.SH SYNOPSIS
.B expire
[
.BI \-d " dir"
]
[
.BI \-f " file"
]
[
.BI \-g " file"
]
[
.BI \-h " file"
]
[
.B \-i
]
[
.B \-N
]
[
.B \-n
]
[
.B \-p
]
[
.BI \-r " reason"
]
[
.BI \-s " size"
]
[
.B \-t
]
[
.BI \-v " level"
]
[
.BI \-w " number"
]
[
.B \-x
]
[
.BI \-z " file"
]
[
.I expire.ctl
]
.SH DESCRIPTION
.I Expire
scans the
.IR history (5)-format
text file
.I <pathdb in inn.conf>/history
and uses the information recorded in it to purge itself of old news articles.
Articles stored using a storage method that has self-expire
functionality are by default not affected by
.IR expire 's
primary behavior (but see the ``\fB\-N\fP'' flag to disable this).  In
this case,
.I expire.ctl
is ignored except ``/remember/'' line for that article;
.I expire
does still probe to see if the article still exists and purges the
relevant history and overview entries if appropriate.
However, if ``groupbaseexpiry'' in
.I inn.conf
is true,
.I expire
acts on all articles as specified by
.I expire.ctl
regardless of whether their storage methods have self-expire
functionality.  In this case, the ``\fB\-e\fP'', \&``\fB\-k\fP'',
``\fB\-N\fP'', ``\fB\-p\fP'', ``\fB\-q\fP'', ``\fB\-w\fP'' and
``\fB\-z\fP'' flags are ignored.
.PP
Note that
.I expire
never purges articles which do not match any entry in
.IR expire.ctl .
.SH OPTIONS
.TP
.B \-d dir
If the ``\fB\-d\fP'' flag is used, then the new history file and database is
created in the specified directory,
.IR dir .
This is useful when the filesystem does not have sufficient space to
hold both the old and new history files.
When this flag is used,
.I expire
leaves the server paused and creates a zero-length file named after the
new history file, with an extension of ``.done'' to indicate that
it has successfully completed the expiration.
The calling script should install the new history file and un-pause the server.
The ``\fB\-r\fP'' flag should be used with this flag.
.TP
.B \-f file
To specify an alternate history file, use the ``\fB\-f\fP'' flag.
This flag is valid when used with the ``\fB\-d\fP'', and the output will
be written to the specified file.
The default without ``\fB\-f\fP'' flag is ``history''.
.TP
.B \-g file
If the ``\fB\-g\fP'' flag is given, then a one-line summary equivalent to the
output of ``\fB\-v\fP 1'', except preceded by the current time, will be
appended to the specified
.IR file .
.TP
.B \-h file
To specify an alternate input text history file, use the ``\fB\-h\fP'' flag.
.I Expire
uses the old
.IR dbz (3)
database to determine the size of the new one.
(If ``\fB\-d\fP'' flag is not used, the output filename will be the same
as the input filename with an extension of ``.n''.)
The default without ``\fB\-h\fP'' flag is
.IR <pathdb\ in\ inn.conf>/history .
.TP
.B \-i
To ignore the old database, use the ``\fB\-i\fP'' flag.
.TP
.B \-N
The control file is normally ignored for articles in storage methods
which have self-expire functionality.
If the ``\fB\-N\fP'' flag is used,
.I expire
still uses the control file for these articles.
.TP
.B \-n
If
.I innd
is not running, use the ``\fB\-n\fP'' flag and
.I expire
will not send the ``pause'' or ``go'' commands.
(For more details on the commands, see
.IR ctlinnd (8)).
Note that
.I expire
only needs exclusive access for a very short time \(em long enough to see
if any new articles arrived since it first hit the end of the file, and to
rename the new files to the working files.
.TP
.B \-p
.I Expire
makes its decisions on the time the article arrived, as found in the
.I history
file.
This means articles are often kept a little longer than with other
expiration programs that base their decisions on the article's posting
date.
To use the article's posting date, use the ``\fB\-p\fP'' flag.
.TP
.B \-r reason
.I Expire
normally sends a ``pause'' command to the local
.IR innd (8)
daemon when it needs exclusive access to the history file, using
the string ``Expiring'' as the reason.
To give a different reason, use the ``\fB\-r\fP'' flag.
The process ID will be appended to the reason.
When
.I expire
is finished and the new history file is ready, it sends a ``go'' command.
See also the ``\fB\-n\fP'' flag.
.TP
.B \-s size
Optimize the new history database for approximately 
.I size
pairs (lines in
.IR history ).
Accurately specifying the size will create a more efficient database.
(The size should be the estimated eventual size of the file, typically
the size of the old file.)
.TP
.B \-t
If the ``\fB\-t\fP'' flag is used, then
.I expire
will generate a list of the tokens that should be removed on its
standard output, and the new history file will be left in
.IR history.n ,
.IR history.n.dir ,
.I history.n.index
and
.IR history.n.hash .
This flag be useful for debugging when used with the ``\fB\-n\fP''
flags.  Note that if the ``\fB\-f\fP'' flag is used, then the
name specified with that flag will be used instead of
.IR history .
.TP
.B \-v level
The ``\fB\-v\fP'' flag is used to increase the verbosity of the program,
generating messages to standard output.
The
.I level
should be a number, where higher numbers result in more output.
Level one will print totals of the various actions done (not valid if a
new history file is not written), level two will print a report on each
individual file, while level five results in multiple lines of output
for every history line processed.
.TP
.B \-w number
Use the ``\fB\-w\fP'' flag to ``warp'' time so that
.I expire
thinks it is running at some time other then the current time.
The value should be a signed floating point number indicating the number
of days to use as the offset.
.TP
.B \-x
If the ``\fB\-x\fP'' flag is used, then
.I expire
will not create any new history files.  This is most useful when combined
with the ``\fB\-n\fP'' and `\fB`\-t\fP'' flags to see how
different expiration policies would change the amount of disk space used.
.TP
.B \-z file
If the ``\fB\-z\fP'' flag is used, then articles are not removed, but their
names are appended to the specified
.IR file .
See the description of
.I delayrm
in
.IR news.daily (8).
.PP
If a filename is specified, it is taken as the control file and parsed
according to the rules in
.IR expire.ctl .
A single dash (``\-'') may be used to read the file from standard input.
If no file is specified, the file
.I <pathetc in inn.conf>/expire.ctl
is read.
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
ctlinnd(8),
dbz(3),
expire.ctl(5),
history(5),
inn.conf(5),
innd(8),
inndcomm(3).
