.\" $Revision $
.TH FASTRM 1
.SH NAME
fastrm \- quickly remove a set of files
.SH SYNOPSIS
.B fastrm
[
.B \-e
]
.SH DESCRIPTION
.I Fastrm
reads a list of article tokens, one per line,
from its standard input and removes them.
.SH OPTIONS
.TP
.B \-e
If the ``\fB\-e\fP'' flag is used,
.I fastrm
will treat an empty input file (\fBstdin\fP) as an error.
This is most useful when 
.I fastrm
is last in a pipeline after a preceding
.BR sort (1)
as if the sort fails, there will usually be no output to become
input of
.IR fastrm .
.SH "EXIT STATUS"
.PP
.I Fastrm
exits with a status of zero if there were no problems, or one if something
went wrong.
Attempting to remove a file that does not exist is not considered a problem.
.SH HISTORY
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
