.\" $Revision$
.TH GREPHISTORY 1
.SH NAME
grephistory \- display file names from Usenet history file
.SH SYNOPSIS
.B grephistory
[
.B \-e
]
[
.BI \-f " filename"
]
[
.B \-i
]
[
.B \-l
]
[
.B \-n
]
[
.B \-q
]
[
.B \-s
]
[
.B \-v
]
[
.I messageid
]
.SH DESCRIPTION
.I Grephistory
queries the
.IR dbz (3)
index into the
.IR history (5)
file for an article having a specified Message-ID.
.PP
If
.I messageid
cannot be found in the database, the program prints ``Not found'' and
exits with a non-zero status.
If
.I messageid
is in the database, the program prints the token of the
article and exits successfully.
.SH OPTIONS
.TP
.B \-e
If the ``\fB\-e\fP'' flag is used, then
.I grephistory
will only print the filename of the token of an existing article.
.TP
.B \-f
To specify a different value for the history file and database, use
the ``\fB\-f\fP'' flag.
.TP
.B \-i
If the ``\fB\-i\fP'' flag is used, then
.I grephistory
will read a list of Message-ID's on standard input, one per line.
Leading and trailing whitespace is ignored, as are any malformed lines.
It will print on standard output those Message-ID's which are not
found in the history database.
This flag is used in processing ``ihave'' control messages.
.TP
.B \-l
If the ``\fB\-l\fP'' flag is used then the entire line from the history
file will be displayed.
.TP
.B \-n
If no pathname exists, the program will print ``/dev/null'' and exit
successfully.
This can happen when an article has been canceled, or if it has been
expired but its history is still retained.
This is default behavior, which can be obtained by using 
the ``\fB\-n\fP'' flag.
.TP
.B \-q
If the ``\fB\-q\fP'' flag is used, then no message is displayed.
The program will still exit with the appropriate exit status.
.TP
.B \-s
If the ``\fB\-s\fP'' flag is used, then
.I grephistory
will read a similar list from its standard input.
It will print on standard output a list of filenames for each article
that is still available.
This flag is used in processing ``sendme'' control messages.
.TP
.B \-v
Each use of the ``\fB\-v\fP'' flag increases the verbosity of
.IR grephistory .
The default level is ``0'', and at present, the maximum useful level
is ``1''.  At level 1, the hash of the Message-ID is printed out for
diagnostic purposes.
This flag is not useful with ``\fB\-s\fP''.
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
dbz(3),
history(5),
inn.conf(5).
