.\" $Revision$
.TH INN.CONF 5
.SH NAME
inn.conf \- configuration data for InterNetNews programs
.SH DESCRIPTION
The file
.IR <PREFIX\ specified\ with\ \-\-prefix\ at\ configure>/etc/inn.conf
is used to determine various parameters.
Blank lines and lines starting with a number sign (``#'') are ignored.
All other lines specify parameters that may be read, and should be of
the following form:
.RS
.nf
name : [optional whitespace] value
.fi
.RE
Everything after the whitespace and up to the end of the line is taken as
the value; multi-word values should not be put in quotes.
The case of names is significant \(em
.I server
is not the same as
.I Server
or
.IR SERVER .
.PP
Some parameters specified in the file may be overridden by environment
variables, and some file parameters may be used to mask real data, such
as when hiding a cluster of hosts behind a single electronic mail hostname.
If the same parameter is specified more than twice, the first one is
used for that parameter.
The current set of parameters is as follows:
.\" BEGIN_AUTO_INSERTED_SECTION from ../include/libinn.h ||DOC
.TP
.I fromhost
This is the name of the host to use when building the From header line.
The default is the fully-qualified domain name of the local host.
The value of the FROMHOST environment variable, if it exists,
overrides this.
.\" END_AUTO_INSERTED_SECTION from ../include/libinn.h ||DOC
.TP
.I moderatormailer
This names the default machine that contains forwarding aliases for all
moderated groups.
It is only used if the
.IR moderators (5)
file doesn't exist, or if the group is not matched by that file.
The value is interpreted as a pattern match; see
.IR moderators (5).
.TP
.I organization
This specifies what to put in the Organization header if it is blank.
The value of the ORGANIZATION environment variable, if it exists,
overrides this.
.TP
.I pathhost
This specifies how to name the local site when building the Path header line.
The default is the fully-qualified domain name of the local host.
.TP
.I server
This specifies the name of the NNTP server to which an article should be
posted.
The value of the NNTPSERVER environment variable, if it exists,
overrides this.
.TP
.I domain
This should be the domain name of the local host.
It should not have a leading period, and it should not be a full host address.
It is used only if the
.I GetFQDN
routine in
.IR libinn (3)
cannot get the fully-qualified domain name by using either the
.IR gethostname (2)
or
.IR gethostbyname (3)
calls.
The check is very simple; if either routine returns a name with a period
in it, then it is assumed to have the full domain name.
.TP
.I overviewmmap
If this is false then nnrpd, expire and makehistory will use regular file access to access overviews 
and overview indices, otherwise it will
.IR mmap (2)
them.  Setting this to true
will give better performance on most system, but some system do have problems
with
.IR mmap (2).
The default value is ``true.''
.TP
.I storageapi
If this is true then all articles will be stored through storage api and
all articles are assumed to be stored through storage api.
The default value is ``false.''
To use storage api, you need to edit storage.ctl to determine which method will
be used.
If storage api is used, any overview database will be stored as unified
overview which is needed if nnrpd will be used.
To specify which index is used for unified overview, you need to edit
.IR <pathetc\ in\ inn.conf>/overview.ctl .
If you run innd as a feeder only, you do not need overview.ctl.
.TP
.I maxforks
How many times to attempt a
.IR fork (2)
before giving up.
.TP
.I maxartsize
The maximum size article (in bytes) that will be accepted by the
server. ``0'' allows any size.
.TP
.I nicekids
If set to anything other than ``0'', all child processes will have
this
.IR nice (1)
value.
.TP
.I mta
This specifies the message transfer agent (mta) to be used when mailing
moderated postings and for use for innmail. The article, with headers and
an added To: line, will be piped into this program and an optional ``%s''
parameter will be replaced with the moderator email address(es). See
.IR moderators (5)
for more info on the moderator email address(es). The ``mta'' option
is compulsory.
.TP
.I mailcmd
This is the path/program to be used for mailing reports and control
messages. The default path is pathbin/innmail.
.TP
.I verifycancels
Set this to ``yes'' to verify that a poster is the person doing the cancel.
This can't be done if the cancel arrives before the article does.
.TP
.I logcancelcomm
Set this to ``yes'' to log ``ctlinnd cancel'' commands to syslog.
.TP
.I wanttrash
Set this to ``yes'' if you want to file articles in unknown newsgroups
into the ``junk'' newsgroup.
.TP
.I remembertrash
Set this to ``no'' if you don't want to record rejected articles in
history. This might cause duplicate articles to be offered to you,
so be careful with it.
.TP
.I linecountfuzz
If this number is set to any number other than ``0'', the article
linecounts are checked against the Lines: header and the header is
adjusted if it is out by more than this amount. A suitable figure
is ``5'' which is the number of suitable .signature lines + 1.
.TP
.I logartsize
Should the article size be put into the article log file. This is
useful for statistics.
.TP
.I logipaddr
Should the IP address of a host be logged rather than the entry in
the Path: line. This is useful for tracking forged postings.
.TP
.I logsitename
Should the site names be put into the article log file.  Those names
are used by
.IR newsrequeue (8).
The default value is ``true''.
.TP
.I overviewname
What file name to use for storing overview data. Defaults to
``.overview''.
.TP
.I extendeddbz
Should overview offset be put into dbz file.
This can be useful to gain overview performance, but note that dbz
file size will be three times.
Whenever
.I extendeddbz
is changed, dbz files should be rebuilt with
.IR makehistory (8)
like this.
.sp 1
.nf
.in +0.5i
makehistory -r -s `cat history | wc -l` -f history
.in -0.5i
.fi
.sp 1
If 
.I storageapi
is ``false'', 
.I extendeddbz
is ignored and always treated as ``false''.
.I extendeddbz
is available only if
.IR <DBZ_TAGGED_HASH\ in\ config.data>
is ``DONT''.
.TP
.I nnrpdoverstats
Should nnrpd overview statistics report be logged to syslog.
This can be useful to see overview performance.
.TP
.I keywords
Should keywords be generated in the overview databases. Must be a boolean
value. Default is false. Changing this requires also changing
.IR <pathetc\ in\ inn.conf>/overview.fmt
and removing the existing overview database.
.I keywords
is available only if
.IR <KEYWORDS\ in\ config.data>
is ``DO''.
.TP
.I keylimit
Maximum number of bytes allocated internally for building keyword data.
.TP
.I keyartlimit
Maximum size of a an article that will have keywords generated for it.
.TP
.I keymaxwords
Maximum number of keywords that will be generated for an article.
.TP
.I pathnews
The news user home directory and sometimes the root of the news
hierarchy.
.TP
.I pathbin
The path to the news binaries.
.TP
.I pathfilter
The path to the perl and TCL filters
.TP
.I pathcontrol
The path to the news control files. The files in this directory represent
the commands that will be executed based on the Control: line in
news articles. Be careful what you put in here, as it can become a
security risk.
.TP
.I pathdb
The path to the database files used and changed by the server. Files
currently in this directory are: active, history* and newsgroups.
Historically, this defaulted to pathetc, but is not split.
.TP
.I pathetc
The news configuration files.
.TP
.I pathrun
Files required while the server is running. This includes locks and
the channel socket.
.TP
.I pathlog
Where the news log files are written.
.TP
.I pathhttp
Where to place any HTML files (e.g: status report). Defaults to
``pathlog''.
.TP
.I pathspool
The root of the news spool hierarchy. This isn't actually used at
the moment.
.TP
.I patharticles
Path where the news articles are stored.
.TP
.I pathoverview
Path to news overview files. Can be set to the same as ``patharticles''
if ``overviewname'' is set to something sensible.
.TP
.I pathoutgoing
Default path for outgoing feed files.
.TP
.I pathincoming
Path where incoming batched news is stored.
.TP
.I patharchive
A path to store archived news.
.PP
The following parameters are used only by 
.I nnrpd
to control high-volume posters via an exponential backoff algorithm.
These parameters are read at 
.I nnrpd
run time.
.PP
Exponential posting backoff works as follows. News clients are 
indexed by IP number (or username, see 
.I backoff_auth 
below). Each time that a specific IP number posts a message, the time of
posting is stored (along with the previous sleep time, see below). 
After a configurable number of posts in a configurable period of time,
.I nnrpd 
will activate posting backoff, and begin to sleep for increasing
periods of time before actually posting anything. Posts will still get
through, but at an increasingly reduced rate.
.PP
The new sleep time is computed based on the difference in time between
the last posting and the current posting, assuming that backoff has
been activated.
.PP
If this difference is less than 
.I backoff_postfast
, the new sleep time will be 1 + (previous sleep time * 
.I backoff_k
). 
.PP
If this difference is less than 
.I backoff_postslow,
but greater than 
.I backoff_postfast,
then the new sleep time will equal the previous sleep time.
.PP
If this difference is greater than 
.I backoff_postslow
then the new sleep time is zero and the number of postings for this IP
number is reset to zero.
.PP
Here are the parameters that control exponential posting
backoff:
.TP
.I backoff_k
An integer value representing the amount to multiply the previous
sleep time by. The default is 1. A value of 2 works to double the
sleep time for each excessive post. 
.TP
.I backoff_postfast
Postings from the same IP which arrive in less than this amount of
time (in seconds) will trigger increasing sleeptime in the backoff
algorithm. The default is 0. 
.TP
.I backoff_postslow
Postings from the same IP which arrive in greater than this amount of
time (in seconds) will reset the backoff algorithm. The default is 1.
Another way to look at this constant is to compute 86400/
.I backoff_postslow
which will give you the maximum number of articles per day that you will allow
users to post.
.TP
.I backoff_trigger
This many postings are allowed before the backoff algorithm is
triggered. The default is 10000. 
.TP
.I backoff_db
Pathname to a directory (must be writable by news) that is to contain
the backoff database. There is no default for this parameter, you must
provide an existing and writable pathname value or users will not be
able to post.
.TP 
.I backoff_auth
This is a boolean value. If on, posting backoffs are indexed on a per
user basis instead of a per IP basis. You must be using authentication
in 
.I nnrpd
for the on value of this constant to have any meaning.
.TP
.I readertrack
This is a boolean value. If on, the article tracking system is
enabled for client reading/posting. See the
.IR nnrpd.track (5)
man page for details. The default is ``no''.
.TP
.I strippostcc
This is a boolean value. If on, To:, Cc: and Bcc: lines are stripped from
local posts through
.IR nnrpd (8).
Default is ``no''. This is aimed mainly at stopping abuse of posting
to moderated newsgroups, whereby those headers are added by the client
and honoured by the mailer when mailed to the moderator.
.PP
The following parameters are used only by
.I innd.
.TP
.I pathalias
This specifies the name prepended before pathhost, if it is not appeared
in the Path header line.
If this is not specified, nothing is prepended before pathhost.
.TP
.I hiscachesize
If this is set to a non-zero number then history file lookups are cached.
This number is the amount of memory to dedicate to the lookup cache in 
kilobytes.  It is generally useful to have memory allocated to history
cache if dbz mmaping is turned on.
.TP
.I xrefslave
If this is true, innd will use the information in the Xref:
header for replication.  And if this is true,
.I nnrpdposthost
should be set to hand articles to the master server.
The default is ``no''.
.TP
.I nnrpdposthost
If this is specified,
.I nnrpd
and
.I rnews
pass articles to the specified host.
This should be set, if
.I xrefslave
is ``true''.
.TP
.I wireformat
If this is true then innd will write articles in wire format.  Wire format
articles are stored with a \\r\\n at the end of each line and with periods
at the beginning of lines doubled.  When used with applications that understand
wire format, this can be considerably more efficent.
If 
.I storageapi
is ``true'', 
.I wireformat
is discarded and articles are always stored in wire format.
.TP
.I writelinks
If this is true innd will write all the crossposts of an article to
the history file, else it will write just the first.  This can be
useful on servers without readers that don't run crosspost and don't
link crossposts.
If 
.I storageapi
is ``true'', 
.I writelinks
is discarded.
.TP
.I timer
If this is '0' or 'off', then performance monitoring will be disabled by
default.  Otherwise, it would be how often to report performance
statistics, in seconds.  If turned on statistics will be logged to syslog.
.TP
.I peertimeout
How long (in seconds) an innd incoming channel can be inactive before
innd closes the channel.
.TP
.I allowreaders
Allow readers to connect even when the server is paused or throttled.
The default is ``no''.
.TP
.I allownewnews
Allow use of the ``NEWNEWS'' command by clients. Allowing this can be
a performance problem on the server, but is recommended by RFC 977.
The default is ``yes''.
.TP
.I chaninacttime
The time (in seconds) to wait between noticing inactive channels.
.TP
.I chanretrytime
How many seconds to wait before a channel restarts.
.TP
.I maxconnections
The maximum number of incoming NNTP connections.
.TP
.I artcutoff
Articles older than this number of days are dropped.
.TP
.I nntplinklog
Should we put nntplink info (filename) into the log.
.TP
.I nntpactsync
How many articles to process before logging NNTP activity.
.TP
.I badiocount
How many read/write failures until a channel is put to sleep or closed.
.TP
.I pauseretrytime
Wait for this many seconds between noticing inactive channels.
.TP
.I blockbackoff
A multiplier (in seconds) for sleep in ``EWOULDBLOCK'' writes.
.TP
.I icdsynccount
How many article writes between active and history file updates.
.TP
.I bindaddress
Which interface IP address
.I innd
should bind to. Must be in dotted-quad format (nnn.nnn.nnn.nnn).
If set to ``all'' or not set at all,
.I innd
defaults to listening on all interfaces.
.TP
.I port
Which TCP port
.I innd
should listen on. Defaults to the 119 - the standard nntp port.
.PP
The following parameters are used only by
.I nnrpd
( or perhaps
.I inews )
when accepting postings from clients:
.TP
.I checkincludedtext
If set to ``yes'' then local postings must have under  50% inclusion
(">") lines.
.TP
.I localmaxartsize
The maximum article size (in bytes) for locally posted articles.
.TP
.I mimeversion
If this parameter is present, then
.I nnrpd
will add the necessary MIME (Multipurpose Internet Mail Extensions)
headers to all any articles that do not have a Mime-Version header.
This parameter specifies the MIME version, and should normally be ``1.0''.
.TP
.I mimecontenttype
If MIME headers are being added, this parameter specifies the value
of the Content-Type header.
The default value is ``text/plain; charset=US-ASCII.''
.TP
.I mimeencoding
If MIME headers are being added, this parameter specifies the value of
the Content-Transfer-Encoding header.
The default value is ``7bit.''
.TP
.I spoolfirst
If this is true then nnrpd will spool new articles with out attempting
to send them to innd first.  If this is false then nnrpd will spool
new articles only after receiving an error trying to send them to
innd.  Setting this to true can be useful if you want nnrpd to
respond to the client as fast as possible, however, nnrpd will not
report articles that are not accepted by innd to the client if they
are spool.
.TP
.I complaints
If this is set, then it contains the value of the X-Complaints-To:
header that will be added to all posts.  If not, then this defaults to
the newsmaster's e-mail address.
.TP
.I articlemmap
If this is false then nnrpd will use regular file access to access 
articles, otherwise it will mmap() the articles.  Setting this to true
will give better performance on most systems, but some systems do have 
problems with mmap().
.TP
.I clienttimeout
How long (in seconds) an nnrpd can be inactive before it exits.
.PP
The following flags are only used by the startup script ``rc.news''.
.TP
.I decnetdomain
.PP
Use this value as the domain to be used for clients connecting via DECNET.
Support for this is only compiled into INN if ``AF_DECnet'' is defined
and compile time.
.TP
.I innflags
The flags to pass to INN on startup. See the
.IR innd (8)
man page for details. The default flags are ``-i0''.
.TP
.I doinnwatch
If set to ``no'' then do not start
.IR innwatch (8).
Default is to start it.
.PP
Note that this file can be identical on all machines in an organization.
.SH EXAMPLE
.RS
.nf
.ta \w'moderatormailer:    'u
fromhost:	foo.com
moderatormailer:	%s@uunet.uu.net
organization:	Foo, Incorporated
#pathhost -- use FQDN.
server:	news.foo.com
domain: foo.com
.fi
.RE
.PP
This file is intended to be fairly static; any changes made to it are
typically not reflected until a program restarts.
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
libinn(3), moderators(5), makehistory(8), newsrequeue(8).
