.\" $Revision$
.TH INN.CONF 5
.SH NAME
inn.conf \- configuration data for InterNetNews programs
.SH DESCRIPTION
The file
.\" =()<.I @<_PATH_CONFIG>@>()=
.I /news/etc/inn.conf
is used to determine various parameters.
Blank lines and lines starting with a number sign (``#'') are ignored.
All other lines specify parameters that may be read, and should be of
the following form:
.RS
.nf
name : [optional whitespace] value
.fi
.RE
Everything after the whitespace and up to the end of the line is taken as
the value; multi-word values should not be put in quotes.
The case of names is significant \(em
.I server
is not the same as
.I Server
or
.IR SERVER .
.PP
Some parameters specified in the file may be overridden by environment
variables, and some file parameters may be used to mask real data, such
as when hiding a cluster of hosts behind a single electronic mail hostname.
The current set of parameters is as follows:
.TP
.I fromhost
This is the name of the host to use when building the From header line.
The default is the fully-qualified domain name of the local host.
The value of the FROMHOST environment variable, if it exists,
overrides this.
.TP
.I moderatormailer
This names the default machine that contains forwarding aliases for all
moderated groups.
It is only used if the
.IR moderators (5)
file doesn't exist, or if the group is not matched by that file.
The value is interpreted as a pattern match; see
.IR moderators (5).
.TP
.I organization
This specifies what to put in the Organization header if it is blank.
The value of the ORGANIZATION environment variable, if it exists,
overrides this.
.TP
.I pathhost
This specifies how to name the local site when building the Path header line.
The default is the fully-qualified domain name of the local host.
.TP
.I server
This specifies the name of the NNTP server to which an article should be
posted.
The value of the NNTPSERVER environment variable, if it exists,
overrides this.
.TP
.I domain
This should be the domain name of the local host.
It should not have a leading period, and it should not be a full host address.
It is used only if the
.I GetFQDN
routine in
.IR libinn (3)
cannot get the fully-qualified domain name by using either the
.IR gethostname (2)
or
.IR gethostbyname (3)
calls.
The check is very simple; if either routine returns a name with a period
in it, then it is assumed to have the full domain name.
.PP
Three parameters are used only by
.I nnrpd
when accepting postings from clients:
.TP
.I mime-version
If this parameter is present, then
.I nnrpd
will add the necessary MIME (Multipurpose Internet Mail Extensions)
headers to all any articles that do not have a Mime-Version header.
This parameter specifies the MIME version, and should normally be ``1.0''.
.TP
.I mime-contenttype
If MIME headers are being added, this parameter specifies the value
of the Content-Type header.
The default value is ``text/plain; charset=US-ASCII.''
.TP
.I mime-encoding
If MIME headers are being added, this parameter specifies the value of
the Content-Transfer-Encoding header.
The default value is ``7bit.''
.PP
The following parameters are used only by
.I innd.
.TP
.I hiscachesize
If this is set to a non-zero number then history file lookups are cached.
This number is the amount of memory to dedicate to the lookup cache in 
kilobytes.  It is generally useful to have memory allocated to history
cache if dbz mmaping is turned on.
.TP
.I xrefslave
If this is true and innd is in slave mode then innd will accept feeds from 
peers that are not it's master and will use the information in the Xref:
header for replication.  
.TP
.I wireformat
If this is true then innd will write articles in wire format.  Wire format
articles are stored with a \\r\\n at the end of each line and with periods
at the beginning of lines doubled.  When used with applications that understand
wire format, this can be considerably more efficent.
.TP
.I timespool
This makes the normal hierarchy a shadow of a time based hierarchy.
The time based hierarchy is two levels.  The first level is upper part
of the time that the article was received in hex, and the second level
is lower part of the same.

The article name name is of the format tttttttt-ssss, where tttttttt
is the time the article was recieved in time_t format, and ssss is a
sequence number to distinguish article that were received in the same second.
.TP
.I writelinks
If this is true innd will write all the crossposts of an article to
the history file, else it will write just the first.  This can be
useful on servers without readers that don't run crosspost and don't
link crossposts.
.TP
.I timer
If this is '0' or 'off', then performance monitoring will be disabled by
default.  Otherwise, it would be how often to report performance
statistics, in seconds.  If turned on statistics will be logged to syslog.
.PP
The following parameters are used only by 
.I nnrpd.
.TP
.I spoolfirst
If this is true then nnrpd will spool new articles with out attempting
to send them to innd first.  If this is false then nnrpd will spool
new articles only after receiving an error trying to send them to
innd.  Setting this to true can be useful if you want nnrpd to
respond to the client as fast as possible, however, nnrpd will not
report articles that are not accepted by innd to the client if they
are spool.
.TP
.I complaints
If this is set, then it contains the value of the X-Complaints-To:
header that will be added to all posts.  If not, then this defaults to
the newsmaster's e-mail address.
.TP
.I articlemmap
If this is false then nnrpd will use regular file access to access 
articles, otherwise it will mmap() the articles.  Setting this to true
will give better performance on most systems, but some systems do have 
problems with mmap().
.TP
.I overviewmmap
If this is false then nnrpd will use regular file access to access overviews 
and overview indices, otherwise it will mmap() them.  Setting this to true
will give better performance on most system, but some system do have problems
with mmap().
.PP
Note that this file can be identical on all machines in an organization.
.SH EXAMPLE
.RS
.nf
.ta \w'moderatormailer:    'u
fromhost:	foo.com
moderatormailer:	%s@uunet.uu.net
organization:	Foo, Incorporated
#pathhost -- use FQDN.
server:	news.foo.com
domain: foo.com
.fi
.RE
.PP
This file is intended to be fairly static; any changes made to it are
typically not reflected until a program restarts.
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
libinn(3), moderators(5).
