.TH INNSTAT 8
.SH NAME
innstat \- print snapshot of INN system
.SH SYNOPSIS
.B innstat
.SH DESCRIPTION
The
.I innstat
script prints a snapshot of the INN system.
It displays the operating mode of the server,
as well as disk usage and the status of all log and lock files.
.SH HISTORY
Written by Landon Curt Noll <chongo@toad.com> and Rich $alz
<rsalz@uunet.uu.net> for InterNetNews.
.SH "SEE ALSO"
innd(8),
news.daily(8),
newslog(5),
nnrpd(8)
