.TH INNWATCH 8
.SH NAME
innwatch \- monitor innd.
.SH SYNOPSIS
.B innwatch 
[ 
.BI -l " logfile"
]
[
.BI -t " seconds"
]
.SH DESCRIPTION
.I Innwatch
is normally started by
.IR rc.news .
It periodically \(em every
.I <innwatchsleeptime in inn.conf>
seconds \(em examines the load average, and the number of free blocks
and inodes on the spool partition, as described by its
control file,
.IR innwatch.ctl .
.PP
If the load gets too high, or the disk gets too full, it throttles the server.
When the condition restores, it unblocks the server.
In addition, on each pass through the loop it will check the
logfile
.I <pathlog in inn.conf>/news.crit
to see if it has been modified, and send mail to the news administrator
if so.
.PP
Upon receipt of an interrupt signal (SIGINT),
.IR innwatch
will report its status in the file
.IR <pathrun\ in\ inn.conf>/innwatch.status .
.SH OPTIONS
.TP
.B \-l logfile
To specify a log file to watch, other than the default of 
.IR news.crit ,
use the ``\fB\-l\fP'' flag.
.TP
.B \-t seconds
To change the period between checks from the default from
.I inn.conf ,
use the ``\fB\-t\fP''
flag.
.SH HISTORY
Written by Mike Cooper <mcooper@usc.edu>, with modifications by
<kre@munnari.oz.au>,  Steve Groom <stevo@elroy.Jpl.Nasa.Gov> and
Christophe Wolfhugel <wolf@pasteur.fr>.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
ctlinnd(8), 
inn.conf(5),
innwatch.ctl(5),
shlock(1).
