.TH INNXBATCH 8
.SH NAME
innxbatch \- send xbatched Usenet articles to a remote NNTP server
.SH SYNOPSIS
.I innxbatch
[
.B \-D
]
[
.BI \-t " timeout"
]
[
.BI \-T " timeout"
]
[
.B \-v
]
.I host
.I file ...
.SH DESCRIPTION
.I Innxbatch
connects to the NNTP server at the specified
.I host
and sends it the specified xbatch files, using the XBATCH extension to
the NNTP protocol. It is normally invoked by a script run out of
.IR cron (8)
that uses
.IR shlock (1)
to lock the host name, followed by a
.IR ctlinnd (8)
command to flush the batchfile.
.PP
Each file is removed after it has been successfully transferred.
.PP
If a communication error such as a
.IR write (2)
failure, or an unexpected reply from the remote server occurs,
.I innxbatch
will stop sending and leave all remaining files untouched for later retry.


.SH OPTIONS
.TP
.B \-t seconds
.I Innxbatch
normally blocks until the connection is made.
To specify a timeout on how long to try to make the connection, use
the ``\-t'' flag.
.TP
.B \-T seconds
To specify the total amount of time that should be allowed for article
transfers, use the ``\-T'' flag.
.br
The default is to wait until an I/O error occurs, or all the articles have
been transferred. If the ``\-T'' flag is used, the time is checked
just before each article is started; it will not abort a transfer that
is in progress.
.TP
.B \-v
Upon exit,
.I innxbatch
reports transfer and CPU usage statistics via
.IR syslog (3).
If the ``\-v'' flag is used, they will also be printed on the standard
output.
.TP
.B \-D
Use the ``\-D'' flag to print debugging information on standard error.
This will show the protocol transactions between
.I innxbatch
and the NNTP server on the remote host.
.SH EXAMPLES
A sample
.I newsfeeds(5)
entry to produce appropriate xbatch files (thanks to Karsten Leipold
<poldi@dfn.de>):
.sp 1
.nf
  nase\e
    :*\e
    :Tc,Wnb\e
.ds R$ <pathbin in inn.conf>
    :\*(R$/batcher \e
.ds R$ <$ac_cv_path_COMPRESS in config.cache>
.ds P$ <pathoutgoing in inn.conf>
       -p "(\*(R$ >\e
       \*(P$/nase.\e$\e$)" \e
       nase.do.main
.fi
.sp 1
A sample script to invoke
.I innxbatch(8)
is:
.sp 1
.nf
  #!/bin/sh
  ##  SH script to send xbatches for a site, wrapped around innxbatch
  ##  Invocation:
  ##     sendxbatches.sh <sitename> <hostname> <xbatch file name> ...

  if [ $# -le 3 ]
  then
	echo "usage: $0 <sitename> <hostname> <xbatch file name>"
	exit 1
  fi

  . <pathbin in inn.conf>/innshellvars

  site="$1"; host="$2"; shift; shift

  ctlinnd flush "$site" \e
  && sleep 5 \e
  && exec $NEWSBIN/innxbatch -v -D "$host" $*
.fi
.SH HISTORY
Written by Stefan Petri <petri@ibr.cs.tu-bs.de>, modelled after
.IR innxmit (8)
and the XBATCH patch for the nntp reference implementation.
.SH "SEE ALSO"
ctlinnd(8),
inn.conf(5),
innd(8),
innxmit(8),
newsfeeds(5),
nntpsend(8),
shlock(1).
