.\" -*- nroff -*-
.TH MAILPOST 1
.SH NAME
mailpost \- feed an email message into a news group
.SH SYNOPSIS
.I mailpost
[
.BI \-r " addr"
]
[
.BI \-f " addr"
]
[
.BI \-a " addr"
]
[
.BI \-d " distribution"
]
[
.BI \-m " mailing-list"
]
[
.BI \-b " database"
]
newsgroups
.SH DESCRIPTION
The
.I mailpost
program reads a properly formatted email message from stdin and feeds it to
inews for posting to a news server. Before feeding the article to inews it
checks that the article has not been seen before, and it changes some headers
(cleans some address headers up and puts ``X-'' in front of unknown headers).
.PP
If the article has been seen before
.RI ( mailpost 
records the message-id of all articles is handles), the the article will be
silently dropped. Other errors will cause the article to be mailed to the
newsmaster.
.PP
Normally mailpost is run by sendmail via an alias entry:
.PP
.RS
.nf
.ds R$ <PREFIX specified with --prefix at configure>/bin
local-mail-wreck-bikes: "|\*(R$/mailpost
         -d local local.mail.rec.bicycles.racing"
.fi
.RE
.PP
.I newsgroups
cannot be multiple groups.  Only one newsgroup name is allowed.
.SH OPTIONS
.TP
.B \-r
If the ``\fB\-r\fP'' flag is used the program will use the given address
as the Path header, if no other value can be determined.
.TP
.B \-f 
The ``\fB\-f\fP'' flag is a synonym for the ``\fB\-r\fP'' flag.
.TP
.B \-a
If the ``\fB\-a\fP'' flag is used the value given is added to the article 
as an Approved header.
.TP
.B \-d
If the ``\fB\-d\fP'' flag is used the value given is added to the article 
as a Distribution header.
.TP
.B \-m
If the ``\fB\-m\fP'' flag is used the value given is added to the articles in a 
Mailing-List header, if a Mailing-List header doesn't already exist.
.TP
.B \-b
IF the ``\fB\-b\fP'' flag is used, then it defines the location of the database 
used to store the message ids of articles sent on. This is to prevent articles
looping around if a news to mail gateway sends them back here. This option may
be required if the mailpost process doesn't have write access to the news tmp
directory (the value of \fBpathtmp\fP in \fBinn.conf(5)\fP.
.SH HISTORY
Written by Paul Vixie long ago and then hacked up by James Brister for INN 
integration.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH FILES
<pathdb in inn.conf>/mailpost-msgid.db	database file
.SH BUGS
Is lacking in configurability.
.SH "SEE ALSO"
active(5), inn.conf(5), nnrpd(8), wildmat(3).
