.\" $Revision$
.TH MAKEHISTORY 8
.SH NAME
makehistory \- tools to recover Usenet history database.
.SH SYNOPSIS
.B makehistory
[
.B \-a
]
[
.B \-b
]
[
.BI \-f " filename"
]
[
.B \-I
]
[
.BI \-l " val"
]
[
.B \-O
]
[
.BI \-T " tmpdir"
]
[
.B \-u
]
[
.B \-x
]
.SH DESCRIPTION
.PP
.I Makehistory
rebuilds the
.IR history (5)
text file.
.IR dbz (3)
database is rebuild by
.IR makedbz (8).
The default name of the text file is
.IR <pathdb\ in\ inn.conf>/history ;
to specify a different name, use the ``\fB\-f\fP'' flag.
.I Makehistory
scans spool through storage manager,
reads each article, and writes a history line for it.
.PP
.I Makehistory
can also rebuild overview database throuth overview method.
.SH OPTIONS
.TP
.B \-a
If the ``\fB\-a\fP'' flag is given then the
.IR history (5)
is opened as appended mode.
.TP
.B \-b
If the ``\-b'' flag is used, then
.I makehistory
will remove any articles that do not have valid Message-ID headers in them.
.TP
.B \-f
If the ``\fB\-f\fP'' flag is used, then the database files are named
.I file.dir
,
.I file.index
and
.IR file.hash .
If the ``\fB\-f\fP'' flag is not used, then a temporary link to the name
.I history.n
is made and the database files are written as
.I history.n.index
,
.I history.n.hash
and
.IR history.n.dir .
.TP
.B \-I
If the ``\fB\-I\fP'' flag is used, then
.IR makehistory (8)
tells overview method not to store overview data under lowest article number in
.IR active(5).
.TP
.B \-l
specifies how many entries before flushing overview data to overview method.
Default is 100000, and 0 will never flush before all entries are created.
This number should be large as possible, since the performance of storing
overview data depends on how small the number of flush.  But note that
you need more space to store temporary overview data.  The estimation of
the space is (300 * val) bytes.
.TP
.B \-O
If the ``\fB\-O\fP'' flag is used, then overview database is also created.
Overview data is needed to provide reader service.  Overview data is not
needed for feed only system.  For ``buffindexed'' ovmethod, all buffers
need to be cleaned before
.IR makehistory (8).
.TP
.B \-T
.I Makehistory
needs to create a temporary file, if overview data is also created.
This file is created in the
.I <pathtmp in inn.conf>
directory.  The ``\fB\-T\fP'' flag may be used to
specify a temporary directory.  In addition, the
.IR sort (1)
that is invoked during the build writes large temporary files (often to
.IR /var/tmp
but see your system manpages).  If the ``\fB\-T\fP'' flag is used, then the
flag and its value will be passed to
.IR sort .
On most systems this will change the temporary directory that
.I sort
uses.
If used, this flag and its value will be passed on to the
.IR sort (1)
command that is invoked during the build.
The default temporary directory for
.I sort
used by
.I makehistory
is
.IR <pathtmp\ in\ inn.conf> .
.TP
.B \-u
If the ``\fB\-u\fP'' flag is given, then
.I makehistory
assumes that
.I innd
is running.
It will throttle the server while scanning, and then
send ``addhist'' commands (see
.IR ctlinnd (8))
to the server for any article that is not found in the
.I dbz
database.
The command ``makehistory\ \-bu'' is useful after a system crash, to delete
any mangled articles and bring the article database back into a more
consistent state.
.TP
.B \-x
If the ``\fB\-x\fP'' flag is used,
.I makehistory
will never write history.
.TP
.SH EXAMPLES
.PP
A typical way to use this program is with the following
.I /bin/sh
commands:
.PP
.RS
.nf
ctlinnd shutdown "Rebuilding history file"
cd <pathetc in inn.conf>
if makehistory \-b \-f history.n -O -l 300000 -I ; then
    :
else
    echo Error creating history file!
    exit 1
f\&i
# The following line can be used to retain expired history
# It is not necessary for the history file to be sorted.
# awk 'NF==2 { print; }' <history >>history.n
# View history file for mistakes.
if makedbz \-s `wc \-l <history` \-f history.n; then
    mv history.n history
    mv history.n.dir history.dir
# if <DBZ_TAGGED_HASH in config.data> is DO
    mv history.n.pag history.pag
# else DONT
    mv history.n.index history.index
    mv history.n.hash history.hash
# fi
f\&i
su - news -c <pathbin in inn.conf>/rc.news
.fi
.RE
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
active(5),
ctlinnd(8),
dbz(3),
history(5),
inn.conf(5),
innd(8),
newsfeeds(5),
makedbz(8).
