.\" $Revision$
.TH NEWSREQUEUE 8
.SH NAME
newsrequeue \- tool to rewrite batchfiles.
.SH SYNOPSIS
.B newsrequeue
[
.BI \-a " active"
]
[
.BI \-h " history"
]
[
.BI \-n " newsfeeds"
]
[
.I input
]
.SH DESCRIPTION
.PP
.I Newsrequeue
can be used to rewrite batchfiles after a system crash.
It reads from the specified
.I input
file, or standard input if no file is specified.
Each line should look like an
.I innd
log entry.
It parses entries for accepted articles, looks up the Message-ID in the
history database to get the filename, and then scans the list of
sites.
.SH OPTIONS
.TP
.B \-a
To specify alternate locations for the active file, use the ``\fB\-a\fP'' 
flag.
.TP
.B \-n
Use the ``\fB\-n\fP'' flag to specify an alternate location for the 
.I newsfeeds(8)
file.
.TP
.B \-h
Use the ``\fB\-h\fP'' flag to specify a different location for
the history database, 
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
active(5),
ctlinnd(8),
dbz(3),
filechan(8),
history(5),
inn.conf(5),
innd(8),
newsfeeds(5),
makeactive(8),
makehistory(8).
