.\" $Revision$
.TH NNRPD.TRACK 5
.SH NAME
nnrpd.track \- file to specify hosts to be tracked by nnrpd.
.SH DESCRIPTION
This file, which is located in
.I <pathetc in inn.conf>,
specifies which hosts are to have their activities recorded during an
.I nnrpd
session.
The
.I nnrpd
server reads it when first spawned by
.IR innd ,
provided
.I readertrack
in
.I inn.conf
is true; otherwise this file is not used.
.PP
Entries consist of one host specification per line, each line having two
fields, separated by a colon:
.RS
.nf

host:identity
.fi
.RE
.PP
The first field is either the FQDN of a host, or a domain name (in 
the form *.domain.com).
.PP
The second field is simply a segment of text which may be used to
more easily identify the client, typically an e-mail address or other
identifying mark.
.PP
For example:
.RS
.nf

nasty.foo.com:nasty@foo.com
*.bar.com:VeryNastyClient
.fi
.RE
.PP
Written by Steve Carrie <stephenc@uk.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
inn.conf(5),
innd(8),
newsfeeds(5),
nnrpd(8),
