.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
''' Revision 1.4  2000/11/14 03:00:12  hkehoe
''' ovdb doc updates
'''
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH ovdb_stat 8 "INN 2.4" "28/Sep/2000" "InterNetNews Documentation"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
ovdb_stat \- Display information from the ovdb database
.SH "SYNOPSYS"
\fBovdb_stat\fR \fB\-Hgci\fR [\fB\-r\fR \fIartnumrange\fR] newsgroup [newsgroup ...]
.PP
\fBovdb_stat\fR \fB\-Hklmtv\fR [\fB\-d\fR \fIdatabase\fR]
.SH "DESCRIPTION"
\fBovdb_stat\fR displays information from the ovdb database: BerkeleyDB
statistics, newsgroup data, and overview records; and optionally
outputs in HTML format.
.SH "OPTIONS"
.Ip "\fB\-g\fR" 4
Newsgroup himark, lowmark, article count, and flag for the given newsgroups
(as stored in the ovdb \*(L"groupinfo\*(R" database) are displayed.
.Ip "\fB\-c\fR" 4
Similar to \fB\-g\fR, except the himark, lowmark, and count are calculated
by actually scanning the overview records and counting them.
This can be a lengthy operation on groups with lots of articles.
.Ip "\fB\-i\fR" 4
Internal data regarding the given newsgroups are displayed.
.Ip "\fB\-r\fR \fIartnumrange\fR" 4
Overview records are retrieved.  The \fIartnumrange\fR parameter may be
a single article number, or a range of articles in the format \f(CWlow-hi\fR.
.Ip "\fB\-H\fR" 4
Output is presented in \s-1HTML\s0 format.
.Ip "\fB\-k\fR" 4
Displays lock region statistics, as returned by the BerkeleyDB \fIlock_stat()\fR
call.
.Ip "\fB\-l\fR" 4
Displays log region statistics, as returned by the BerkeleyDB \fIlog_stat()\fR
call.
.Ip "\fB\-m\fR" 4
Displays global memory pool statistics, as returned by the
BerkeleyDB \fImemp_stat()\fR call.
.Ip "\fB\-M\fR" 4
Same as \fB\-m\fR, and also displays memory pool statistics for each
database file.
.Ip "\fB\-t\fR" 4
Displays log region statistics, as returned by the BerkeleyDB \fItxn_stat()\fR
call.
.Ip "\fB\-v\fR" 4
Displays ovdb version, and BerkeleyDB version.
.Ip "\fB\-d\fR \fIdatabase\fR" 4
Displays information about the given database, as returned by the
BerkeleyDB db->\fIstat()\fR call.  This operation may take a long time
on busy systems (several minutes or more).
.SH "WARNINGS"
ovdb_stat may be safely killed with the INT, TERM, or HUP signals.
It catches those signals and exits cleanly.
Do not kill ovdb_stat with other signals, unless absolutely necessary,
because it may leave stale locks in the DB environment.
.SH "HISTORY"
Written by Heath Kehoe <hakehoe@avalon.net> for InterNetNews.
.SH "SEE ALSO"
\fIovdb\fR\|(5)

.rn }` ''
.IX Title "ovdb_stat 8"
.IX Name "ovdb_stat - Display information from the ovdb database"

.IX Header "NAME"

.IX Header "SYNOPSYS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\fB\-g\fR"

.IX Item "\fB\-c\fR"

.IX Item "\fB\-i\fR"

.IX Item "\fB\-r\fR \fIartnumrange\fR"

.IX Item "\fB\-H\fR"

.IX Item "\fB\-k\fR"

.IX Item "\fB\-l\fR"

.IX Item "\fB\-m\fR"

.IX Item "\fB\-M\fR"

.IX Item "\fB\-t\fR"

.IX Item "\fB\-v\fR"

.IX Item "\fB\-d\fR \fIdatabase\fR"

.IX Header "WARNINGS"

.IX Header "HISTORY"

.IX Header "SEE ALSO"

