.\" $Revision$
.TH OVERVIEW.CTL 5
.SH NAME
overview.ctl \- configuration file for unified overview
.SH DESCRIPTION
.I overview.ctl
is obsolete.  This file used to be used for unified overview, which is
no longer present in INN.  Instead, there are multiple different overview
methods, some of which have their own configuration files.
.SH SEE ALSO
.IR buffindexed.conf "(5), " ovdb (5).
