.\" $Revision$
.TH OVERVIEW.CTL 5
.SH NAME
overview.ctl \- configuration file for unified overview
.SH DESCRIPTION
The file
.\" =()<.I @<_PATH_OVERVIEWCTL>@>()=
.I /var/news/etc/overview.ctl
is required if the new storage API is used on machines running
.IR nnrpd (8).
Optional on feed-only machines.
.PP
The traditional overview database was written by an external program
.IR overchan (8),
but with the unified overview, this is now done by
.IR innd (8).
This is because the overview offset is written into a token, which
is stored as the 3rd field of each
.IR history (5)
entry.
.IR Overchan (5)
is still needed to store the overview index and will require an
entry in the
.IR newsfeeds (5)
file. If the overview index is not created, the articles will not
be available through
.IR nnrpd (8).
.PP
Overview entries are now expired with the normal
.IR expire (8)
program and the overview index is expired with
.IR expireindex (8)
.PP
The file consists of a series of lines;
blank lines and lines beginning with a number sign (``#'') are ignored.
The order of lines in this file is important.
.PP
Each line is formatted as:
.PP
.RS
.nf
index_number:wildmat
.fi
.RE
.PP
The ``index_number'' is a number >= 0 and <255 and ``wildmat''
refers to a newsgroup pattern that will be parsed with
.IR wildmat (3).
Matching newsgroup is against newsgroup name in ``Xref'' header, 
not ``Newsgroups'' header.
\&``!'' and ``@'' are allowed at the start of the wildmat and
refer to pattern exclusions. See
.IR newsfeeds (5)
for a description of their use.
.PP
If a newsgroup matches wildmat pattern, overview data is stored
in
.\" =()<.IR @<_PATH_OVERVIEWDIR>@/index_number/overview .>()=
.IR /var/news/spool/over.view/index_number/overview .
Note that the file is interpreted in order and first match line
is used to store overview data.
.PP
If a newsgroup does not match any wildmat pattern in
any line, no overview data is stored for it and no articles can be
retrieved from it for reading.
.PP
If the file is changed, it can be reloaded into INN using
\&``ctlinnd reload overview.ctl reason'' (see
.IR ctlinnd (8)).
.SH HISTORY
Written by Katsuhiro Kondou <kondou@nec.co.jp> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
ctlinnd(8),
expire(8),
expireindex(8),
expireover(8),
innd(8),
history(5),
newsfeeds(5),
nnrpd(8),
overchan(8),
wildmat(3).
