.\" $Revision$
.TH OVERCHAN 8
.SH NAME
overchan \- update the news overview database
.SH SYNOPSIS
.B overchan
[
.BR file \ ...
]
.SH DESCRIPTION
.I Overchan
reads article data from
.I files
or standard input if none are specified.
(A single dash in the file list means to read standard input.)
It uses this information to update the news overview database.
.I Overchan
was originally designed to be used by InterNetNews or the C News ``mkov'' packages
to update the database as the articles come in.
For current INN, the database is stored in a selected overview method.
This can be done within
.IR innd (8)
itself, but
.IR overchan (8)
can be used instead, if
.I <useoverchan in inn.conf>
is ``true'' and appropriate setup is done in
.IR newsfeeds ,
for example:
.PP
.RS
overview!:*:Tc,WnteO:<pathbin in inn.conf>/overchan
.RE
.PP
.I Overchan
input data consists of a line of text, separated into four parts by a space.
The first part is a token for the article.
The second part is time when the article was received.
The third part is time when the article will be expired (which represents
the Expires header).
The fourth part is the data to be stored.
.PP
The data in the overview files should be expired by running
.IR expireover (8).
This is normally done by adding the ``expireover'' flag to the
.IR news.daily (8)
invocation.
.PP
.SH HISTORY
Written by Rob Robertson <rob@violet.berkeley.edu>
and Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
expireover(8),
inn.conf(5),
news.daily(8),
newsfeeds(5).
