.\" $Revision$
.TH PRUNEHISTORY 8
.SH NAME
prunehistory \- remove tokens from Usenet history file
.SH SYNOPSIS
.B prunehistory
[
.BI \-f " filename"
]
[
.B \-p
]
.SH DESCRIPTION
.I Prunehistory
modifies a
.IR history (5)-format
text file to ``remove'' a set of tokens from it.
The tokens are removed by overwriting them with spaces, so that the
size and position of any following entries does not change.  This has an
effect similar to expiring the article, in that it is still mentioned in
the history database but cannot be retrieved.
.PP
.I Prunehistory
reads the standard input.
The input is taken as a set of lines.
Blank lines and lines starting with a number sign (``#'') are ignored.
All other lines are should consist of a Message-ID followed by zero or
more other fields (which are ignored).
.PP
The Message-ID is used as the
.IR dbz (3)
key to get an offset into the text file.
.PP
Since
.IR innd (8)
only appends
to the text file,
.I prunehistory
does not need to have any interaction with it.
.SH OPTIONS
.TP
.B \-p
.I Prunehistory
will normally complain about lines that do not follow the correct format.
If the ``\-p'' flag is used, then the program will silently print any
invalid lines on its standard output.
(Blank lines and comment lines are also passed through.)
This can be useful when
.I prunehistory
is used as a filter for other programs such as
.IR reap .
.TP
.BI \-f " filename"
The default name of the history file is
.IR <pathdb\ in\ inn.conf>/history ;
to specify a different name, use the ``\-f'' flag.
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
dbz(3),
history(5),
inn.conf(5),
innd(8).
