.TH SCANLOGS 8
.SH NAME
scanlogs \- summarize INN log files.
.SH SYNOPSIS
.B scanlogs
[
.B norotate
]
[
.B nonn
]
.SH DESCRIPTION
.I Scanlogs
summarizes the information recorded in the INN log files (see
.IR newslog (5)).
By default, it also rotates and cleans out the logs.
It is normally invoked by the
.IR news.daily (8)
script.
.SH KEYWORDS
.PP
The following keywords are accepted:
.TP
.I norotate
Using this keyword disables the rotating and cleaning aspect of the log
processing: the logs files are only scanned for information and no contents
are altered.
.TP
.I nonn
Normally the
.I nn
log file is scanned and rotated.
Using this keyword disables this function.
.PP
If
.I scanlogs
is invoked more than once a day, the ``norotate'' keyword should be used
to prevent premature log cleaning.
.SH HISTORY
Written by Landon Curt Noll <chongo@toad.com> and Rich $alz
<rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
innd(8)
newslog(5),
news.daily(8),
nnrpd(8).
