.\" $Revision$
.TH SIMPLEFTP 1
.SH NAME
simpleftp \- rudimentary ftp client
.SH SYNOPSIS
.B simpleftp
.I ftp://...
[ ... ]
.SH DESCRIPTION
.B simpleftp
is a
.B perl
script that provides basic support for fetching files with FTP in a
batch oriented fashion.  It takes one or more ftp URLS on the command
line.  The file(s) will be retrieved from the remote server and placed
in the current directory with the same basename as on the remote;
e.g., ftp://ftp.isc.org/pub/usenet/CONFIG/active.gz is stored as
active.gz in the current directory.
.SH BUGS
.B simpleftp
is an extremely poor substitute for more complete programs like the
freely available
.B wget
or
.B ncftp
utilities.  It was written only to provide elementary support in INN
for non-interactive fetching of the files in
ftp://ftp.isc.org/pub/usenet/CONFIG/ without requiring administrators
to install yet another package.  Its shortcomings as a general purpose
program are too numerous to mention, but one that stands out is that
.B simpleftp
does not understand the complete syntax of URLs, only the hostname and
pathname parts -- it will not understand username, password, port or
parameter strings.
.SH HISTORY
Tossed off by David C Lawrence <tale@isc.org> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.SH "SEE ALSO"
.IR actsync (8).
