.\" $Revision$
.TH SM 8
.SH NAME
sm \- command line interface to the storage manager
.SH SYNOPSIS
.I sm
[
.B \-d
]
[
.B \-i
]
[
.B \-q
]
[
.B \-R
]
[
.B \-r
]
[
.B \-H
]
[
.B \-S
]
[
.I token
] ...
.SH DESCRIPTION
The
.I sm
program provides a command line interface to the storage manager.
If no options are specified, 
.I sm
by default shows the entire article associated with the token.
The
.I token
is a token of the article, as is stored as the third field of history line.
Tokens can be given on the commandline; if none are, they are read from
standard input, one per line.
.SH OPTIONS
.TP
.B \-d \-r
If the ``\fB\-d\fP'' or ``\fB\-r\fP'' flag is used,
then the program removes the article associated with the token.
.TP
.B \-i
If the ``\fB\-i\fP'' flag is used,
then the program shows only the newsgroup name and article number
associated with the token.
.TP
.B \-q
If the ``\fB\-q\fP'' flag is used,
all error messages except usage are suppressed.
.TP
.B \-R
If the ``\fB\-R\fP'' flag is used,
then the program shows the raw article spooled into storage method
associated with the token.
.TP
.B \-S
A spool file in rnews format will be emitted on stdout.
.TP
.B \-H
Only the headers will be printed.
.SH HISTORY
Written by Katsuhiro Kondou <kondou@nec.co.jp> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.SH "SEE ALSO"
rnews(1), history(5), storage.conf(5).
