.\" $Revision$
.TH SM 8
.SH NAME
sm \- command line interface to the storage manager
.SH SYNOPSIS
.I sm
[
.B \-q
]
[
.B \-R
]
[
.B \-r
]
[
.B \-d
]
[
.B \-o
]
.I token
[
.I token
] ...
.SH DESCRIPTION
The
.I sm
program provides a command line interface to the storage manager.
If no options are specified, 
.I sm
shows the whole article associated with the token.
The
.I token
is a token of the article which is stored by storage api, and it is stored
as the third field of history line.
.SH OPTIONS
.TP
.B \-q
If the ``\fB\-q\fP'' flag is used,
all error messages except usage are suppressed.
.TP
.B \-R
If the ``\fB\-R\fP'' flag is used,
then the program shows the raw article spooled into storage method
associated with the token.
.TP
.B \-d \-r
If the ``\fB\-d\fP'' or ``\fB\-r\fP'' flag is used,
then the program removes the article associated with the token.
.TP
.B \-o
If the ``\fB\-o\fP'' flag is used,
then the program shows the overview data associated with the token.
.SH HISTORY
Written by Katsuhiro Kondou <kondou@nec.co.jp> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.SH "SEE ALSO"
history(5), overview.ctl(8), storage.conf(5).
