.TH STARTINNFEED 8 "Nov 7, 1997"
.SH NAME
startinnfeed \- setuid root program to start innfeed
.SH SYNOPSIS
.B startinnfeed
.RB [innfeed-options]
.sp
.B startinnfeed
.RB imapfeed
.RB [imapfeed-options]
.SH DESCRIPTION
.B Startinnfeed
sets all resources (files opened, memory usage) to unlimited. It then executes
innfeed(8) with the options specified.

If the first argument to 
.B startinnfeed
is ``\fIimapfeed\fP'' then 
.B imapfeed 
will be executed (instead of innfeed(8)) with the remaining argument as
options.
.SH HISTORY
Written by James Brister.
.SH "SEE ALSO"
.BR innfeed (8)
