.\" $Revision$
.TH STORAGE.CTL 5
.SH NAME
storage.ctl \- configuration file for storage manager
.SH DESCRIPTION
The file
.I <pathetc in inn.conf>/storage.ctl
is obsolete, and has been replaced by
.I <pathetc in inn.conf>/storage.conf.
See
.IR storage.conf (5)
for a description of the new format.
.SH "SEE ALSO"
storage.conf(5),
cycbuff.conf(5),
expire.ctl(5),
inn.conf(5),
innd(8),
newsfeeds(5),
wildmat(3).
