.TH TALLY.UNWANTED 8
.SH NAME
tally.unwanted \- keep track of unwanted newsgroups.
.SH SYNOPSIS
tally.unwanted
.SH DECSRIPTION
.I tally.unwanted
is normally invoked by
.IR scanlogs (8). 
It parses the article log file to update the cumulative list of
articles posted to unwanted newsgroups,
.IR unwanted.log .
.SH HISTORY
Written by Landon Curt Noll <chongo@toad.com> and Rich $alz
<rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
innd(8)
innlog.pl(8),
news.daily(8),
newslog(5),
nnrpd(8),
scanlogs(8),
tally.control(8),
writelog(8).
