.TH TALLY.CONTROL 8
.SH NAME
tally.control \- keep track of newsgroup creations and deletions.
.SH SYNOPSIS
tally.control
.SH DECSRIPTION
tally.control is normally invoked by
.IR scanlogs (8). 
It
reads its standard input, which should be the
.I newgroup.log
and
.I rmgroup.log
log files.
It updates the cumulative list of newsgroup creations and deletions,
.IR control.log .
.SH HISTORY
Written by Landon Curt Noll <chongo@toad.com> and Rich $alz
<rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
newslog(5),
news.daily(8),
scanlogs(8),
tally.unwanted(8),
writelog(8).
