.TH WRITELOG 8
.SH NAME
writelog \- add a entry to an INN log file.
.SH SYNOPSIS
.B writelog
.I name
.I text...
.SH DESCRIPTION
.PP
The
.I writelog
script is used to write a log entry or send it as mail.
The
.I name
parameter specifies the name of the log file where the entry should
be written.
If it is the word ``mail'' then the entry is mailed to the news administrator,
.IR <USER\ specified\ with\ \-\-with\-news\-master\ at\ configure> .
The data that is written or sent consists of the
.I text
given on the command line, followed by standard input indented by
four spaces.
.IR Shlock (1)
is used to avoid simultaneous updates to a single log file.
.SH HISTORY
Written by Landon Curt Noll <chongo@toad.com> and Rich $alz
<rsalz@uunet.uu.net> for InterNetNews.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id$
.SH "SEE ALSO"
innd(8),
innstat(8),
news.daily(8),
newslog(5),
nnrpd(8),
scanlogs(8).
